### ISSUE TITLE
Error when sharing a draft app to a user that is not a member of app's organization

### ISSUE THREAD

**Issue by jimmyshiau** [quire-api/quire-api#16]
I am trying to allow this app in a different project using this link and get an error:
```{"error":"access_denied","error_description":"User is unauthorized"} ```

**Comment by jimmyshiau** [comment]
It was caused by using share link by non org member user
In final spec will allow all quire user can use dev app
need to double check

**Comment by tomyeh** [comment]
We'll allow user to access a draft app as long as he got the share link. That is, it is developer's job to keep the URL from misuse.
