### ISSUE TITLE
[Doc] Introduce activity's type

### ISSUE THREAD

**Issue by jimmyshiau** [quire-api/quire-api#17]
https://quire.io/dev/api/#webhook
For now we only have 
```"type": 0```
Need doc to introduce the code

**Comment by eyrewiut** [comment]
Is there any progress on this? It would be helpful to know have a list of activities and their codes.
Thanks

**Comment by mniederl** [comment]
We are approaching 3 years since this issue was raised and I still can't find any documentation on it.

The only listing I found (end of the referenced comment) is no longer up to date:
https://github.com/quire-api/quire-api/issues/35#issuecomment-554848880

**Comment by anastasiagrishina-make** [comment]
Would really appreciate documentation on webhook `activity types`. Are there any plans for this?

**Comment by tomyeh** [comment]
Activity Types added: https://github.com/quire-api/quire-api/blob/master/docs/activity_types.md
