### ISSUE TITLE
quota/rate limit exceeded error status/message inconsistent

### ISSUE THREAD

**Issue by cor3000** [quire-api/quire-api#21]
when requesting the API more than 60 times per minute, the following error status/message is returned

`400,Bad Request,/task/{taskOid},{"code":469,"message":"You cannot access Quire API more than <b>600</b> times in a minute. Please <a href=\"mailto:support@quire.io\">contact us</a> for more quota."}`

HTTP status code should be 429 instead of 400 and the message should be 60 and not 600

Besides it's not clear what's the difference between error code 469 and 429

The status codes only mention (https://quire.io/dev/api/#status-codes):

 - 429 | Too Many Requests | Exceeded the rate limit for API calls

While the error responses contain 2 separate codes (https://quire.io/dev/api/#error-responses)

- 429 | Too many invocations.
- 469 | Quota exceeded.

**Comment by tomyeh** [comment]
Both issues were fixed. It shall be available in the next update (scheduled tomorrow).

429: too many invocations, i.e., API was invoked too many times
469: quota like number of tasks, project.... In short, anything other than 429.
