### ISSUE TITLE
no easy way to identify (tag) ids

### ISSUE THREAD

**Issue by davismj** [quire-api/quire-api#31]
The add task api requires an array of tag oids for the tags field, yet the only way to find the tag oids seems to be through the api.

Since tag names are unique and since oids are in a particular format, it would be nice to support oid-or-tag-name in the tags array.

**Comment by davismj** [comment]
On second thought, this is true with a lot of things in the app. Project ids are unavailable as well, but the api supports a project-id-or-name behavior.

What about adding a user setting "developer mode": true that can be configured in the profile which displays id fields everywhere in the application. Set to false by default so the average user doesn't see or get confused by the ids.

**Comment by cor3000** [comment]
updated api docs: https://quire.io/dev/api/#operation--task--oid--put
