### ISSUE TITLE
Support CORS for API requests from a browser client

### ISSUE THREAD

**Issue by cor3000** [quire-api/quire-api#44]
Accessing the quire-api from a browser client directly (via XHR/fetch) is currently blocked by missing CORS policies (even with a valid access token)

Consider handling CORS requests and respond with the necessary response headers (allow-origin etc)

If feasible/needed make it configurable at project level/app level?

[related SO question](https://stackoverflow.com/q/65500179/4740707)

**Comment by khaledbnmohamed** [comment]
@tomyeh  Is there any reference or any reason for closing the issue without explanation? as I have the same problem and I had to use a middleware

**Comment by cor3000** [comment]
CORS is now enabled for quire-api requests  ... sorry about the delay, give us some sleep ;)

examples:

using fetch()

```
const headers = {"Authorization": "Bearer YOUR_ACCESS_TOKEN", "content-type": "application/json"};
const resp = await fetch("https://quire.io/api/task/list/id/test-app", {headers, method: "GET", mode: "cors"});
const json = await resp.json();
```
using XHR

```
var req = new XMLHttpRequest();
req.addEventListener("load", function () {
    console.log(this.responseText)
});
req.open("GET", "https://quire.io/api/task/list/id/test-app");
req.setRequestHeader("Content-Type", "application/json");
req.setRequestHeader("Authorization", "Bearer YOUR_ACCESS_TOKEN");
req.send();
```

**Comment by tomyeh** [comment]
> @tomyeh Is there any reference or any reason for closing the issue without explanation? as I have the same problem and I had to use a middleware

Sorry, I didn't notice it is closed via Github's hook (of a private repos).
Yes, as Robert pointed out, it is ready online.
