### ISSUE TITLE
Create task returns status code 403 when due date is set

### ISSUE THREAD

**Issue by karlhaas** [quire-api/quire-api#49]
Although the permission to schedule tasks is granted, the API returns status code 403 when setting a due date.
It works without the due date.

**Comment by jimmyshiau** [comment]
Hi @karlhaas 

If the token has no permission to edit due (e.g. *Limited* user role), the API will return 403

**Comment by karlhaas** [comment]
Hi @jimmyshiau 

The App has the following permissions:
![image](https://user-images.githubusercontent.com/7677394/130205781-ab8954e3-70b6-4769-b108-b5738eb7f90a.png)

When requesting the authorization code, it looks like:
![image](https://user-images.githubusercontent.com/7677394/130206052-dfce74ad-d609-4d64-b6b2-f60a5b7e44f7.png)

Where can I manage the the permission to edit due?

**Comment by jimmyshiau** [comment]
Hi @karlhaas
Does the token user is an organization or project admin member?
When update the task under the organization or project

**Comment by karlhaas** [comment]
@jimmyshiau The user is admin in the organization and the project

**Comment by karlhaas** [comment]
As soon as I add a due date the status is 403 and the body of the response is:
```
<!DOCTYPE html>

<html>
	<head>
		<title>Quire</title>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
		<link rel="stylesheet" type="text/css" href="/s/css/lato-2.010.min.css" >
		<link rel="stylesheet" type="text/css" href="/s/css/bootstrap/bootstrap.min.css" >
		<link rel="stylesheet" type="text/css" href="/s/css/error.css" >
	</head>

	<body class="not-found-page static">
		<header id="header-wrapper" class="header-wrap navbar navbar-default navbar-fixed-top">
	        <div id="header" class="container">
	          	<div id="quire-logo" class="navbar-header">
				  	<h1 class="quire-logo-icon">
					    <em>
					      	<a id="home" href="/" title="Quire">
					       		<img src="/s/img/quire_logo.svg" alt="Quire">
					      	</a>
					    </em>
				  	</h1>
				</div>
	    	</div>
      	</header>
		<div id="wrap">
			<div id="body" class="container">
				<div class="row">
					<div class="col-xxs-offset-3 col-xxs-18 col-sm-offset-0 col-sm-12">
						<div>
							<h2>The page you are looking for cannot be found.</h2>
							<p>If you need assistance, please <a href="mailto:support@quire.io">contact us.</a></p>
							<h3>Here are a few links that may be helpful:</h3>
							<ul class="list-unstyled">
								<li>
									<a href="/">Home</a>
								</li>
								<li>
									<a href="mailto:support@quire.io">Feedback</a>
								</li>
								<li>
									<a href="/faq">FAQ</a>
								</li>
							</ul>
							
						</div>
					</div>
					<div class="hidden-xxs hidden-xs col-sm-12">
						<div class="img">
							<video muted playsinline loop autoplay
								 poster="/s/img/website/error_404.png"
								 src="/s/img/website/error_404.mp4"></video>
						</div>
					</div>
				</div>
			</div>
		</div>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-48347893-1"></script>
<script src="/s/js/jquery-3.6.0.min.js"></script>
<script src="/s/js/pack.min.js"></script>
	</body>
</html>
```

**Comment by jimmyshiau** [comment]
Can you double check the http request? 
it shall send a `PUT` request to `https://quire.io/api/task/id/{projectId}/{taskId}`
https://quire.io/dev/api/#operation--task-id--projectId---id--put

**Comment by karlhaas** [comment]
I'm using a `POST` to `https://quire.io/api/task/{oid}`
https://quire.io/dev/api/#operation--task--oid--post

**Comment by jimmyshiau** [comment]
I tried `Post` with  `{"name": "abc","due": "2020-08-20T00:00:00.000Z"}`
It works fine, do you select `All` or only an organization or a project?

![image](https://user-images.githubusercontent.com/1056469/130260268-7a3acfa7-30df-4621-9398-8ea7900f9743.png)

**Comment by karlhaas** [comment]
@jimmyshiau thanks for your help. I found the problem. I always checked the permissions in the app view of the organisation `https://quire.io/apps/dev/{name}` but not the app of my user `https://quire.io/r/setting?tab=app`.

The problem then is, that the app permissions are created with the granted permissions of the first call. Subsequent calls including more permissions do not update the permissions of the created app itself.

I close this one ...
