### ISSUE TITLE
bug Recurring End date

### ISSUE THREAD

**Issue by nastyagrishina** [quire-api/quire-api#50]
During the implementation of the **"Add a new task."** endpoint, I run into a bug. Property **"end:"** of the object **"recurring:"** returns a changed value **in the response on the "Add a new task." call.** 

What's happening: 

I'm sending -> "end": "2020-12-22T00:00:00.000Z" and in the response 

I'm getting -> "end": "137660-11-29T07:50:52.241Z"

**Comment by tomyeh** [comment]
This issue has been fixed and available online.

Sorry for the late response.
