### ISSUE TITLE
Update a Comment pinned: true throwing an error.

### ISSUE THREAD

**Issue by nastyagrishina** [quire-api/quire-api#52]
Endpoint: **Update a Comment**

When I am trying to update comment with **pinned: true**, I am getting an error:_[400] type 'DateTime' is not a subtype of type 'int' in type cast_. It doesn't matter if the comment is pinned for the first time or it's already pinned - the error is the same. 
Pinned works only with **false** value.

`{
    "_engineData": {
        "calledAt": "2021-11-26T14:05:21.442Z"
    },
    "response": {
        "status": 400,
        "headers": {
            "server": "nginx",
            "date": "Fri, 26 Nov 2021 14:05:21 GMT",
            "content-type": "application/json; charset=utf-8",
            "transfer-encoding": "chunked",
            "connection": "close",
            "set-cookie": [
                "DARTSESSID=8c1466d3c3ce77236167d7ad9e5b5aa1; Path=/; HttpOnly"
            ]
        },
        "body": {
            "code": 400,
            "message": "type 'DateTime' is not a subtype of type 'int' in type cast"
        },
        "_engineData": {
            "calledAt": "2021-11-26T14:05:22.094Z"
        }
    },
    "request": {
        "url": "https://quire.io/api/comment/id/Say_project/OTt2G24MK97VNYWkAjW34_yc",
        "headers": {
            "user-agent": "personal/production",
            "authorization": "***",
            "content-type": "application/json"
        },
        "method": "PUT",
        "body": {
            "pinned": true,
            "description": "Updated comment"
        }
    }
}
`

**Comment by tomyeh** [comment]
This issue has been fixed and is available online.
Thanks for reporting this issue.
