### ISSUE TITLE
"Add a new tag" API returns error 403

### ISSUE THREAD

**Issue by anastasiagrishina-make** [quire-api/quire-api#59]
Quire API returns error 403 every time I try to add/update/delete a tag. Meanwhile, for example, "delete a task" endpoint works fine for me. I have all possible permissions. When I try to revoke permissions in my Quire account, the page gets stuck and nothing happens. 

Here is my request:
`curl -X POST 'https://quire.io/api/tag/Bz3MjEMiJWeTWKXshXpvyA_~' -H 'user-agent: Make/production' -H 'authorization: ***' -H 'content-type: application/json' -d '{"name":"ID tags","color":"00","global":true}'`

 
<img width="572" alt="Screenshot 2022-11-12 at 13 01 51" src="https://user-images.githubusercontent.com/113098610/201472986-598f303c-5372-4542-a43b-876faad842c2.png">

**Comment by tomyeh** [comment]
This issue has been fixed and is available online.
Thanks for reporting this issue.

**Comment by anastasiagrishina-make** [comment]
@tomyeh Experiencing the same issue with webhook now... Can you take a look at it also? Thank you.

**Comment by tomyeh** [comment]
Webhook? Could you show me how to reproduce it?

**Comment by anastasiagrishina-make** [comment]
@tomyeh Sorry, it was a mistake.
The Webhook URL wasn't specified in the app setting and Quire server was returning empty [403] response. If you could provide error message for [403], it would be super helpful for the future. 

But Webhook is working:)
