### ISSUE TITLE
Localhost redirect URLs no longer work

### ISSUE THREAD

**Issue by dalemyers** [quire-api/quire-api#61]
These used to work, but now no longer do. Being unable to use localhost means that you cannot easily create a tool which runs on a users machine. We have various tools like this, and our auth process means we have to redirect to something else, then copy the code from the URL and enter it in as a config value. Being able to redirect to localhost would make this process much simpler.

**Comment by tomyeh** [comment]
Fixed.

> It was caused our introduction of SSRF protection. However, the redirect URL is not related to SSRF, so we shall allow it.

It will be available in the next update, which is scheduled on Aug 12, 2023.
