### ISSUE TITLE
[Open API] Support get tasks by board

### ISSUE THREAD

**Issue by jimmyshiau** [quire-api/quire-api#7]
https://stackoverflow.com/questions/58180653/new-api-add-a-task-to-a-board

(/task/list/id/test-app/xxxBoard)
(/task/list/board-oid)

**Comment by cor3000** [comment]
alternative:
extend the `/task/search` api

`/task/search/{projectOid}?board={boardOid}`
`/task/search/id/{projectId}?board={boardOid}`

**Comment by cor3000** [comment]
[related stackoverflow topic](https://stackoverflow.com/posts/58236200/edit)
